### ISSUE TITLE
Command dev should be compatible with relative path for services from app folder

### ISSUE THREAD

**Issue by antho1404** [liteflow-labs/liteflow-js#13]
---

Migrated from https://github.com/mesg-foundation/js-sdk/issues/240
Originally created by @NicolasMahe on *Wed, 15 Apr 2020 12:19:53 GMT*

---
Currently, the command `dev` is using the path of the current folder (the path of the terminal) to search the source of the services indicated in the process files.
But if the terminal is not executed in the same folder as the process files, then the relative path to the services doesn't work.
For example:
`app/process.yml`:
```yaml
name: test
steps:
  - type: trigger
    key: interval
    instance:
      src: services/service-emit-event-interval
    eventKey: every_10_seconds
  - type: task
    instance:
      src: services/service-js-function
    taskKey: execute
    inputs:
      code: "module.export = function(value) { return true }"
      inputs:
        foo: 42
```
command that doesn't work:
```
mesg-cli dev ./app
```
command that work:
```
cd app
mesg-cli dev ./
```
