### ISSUE TITLE
Improve process service path detection

### ISSUE THREAD

**Issue by NicolasMahe** [liteflow-labs/liteflow-js#150]
it seems value `services/greeter` is considered as a git url.
I got the error `'git clone' failed with status 128 ` when running command dev with following process:
```yml
name: process
steps:
  - type: trigger
    instance:
      src: services/greeter
    eventKey: greets
  - type: task
    instance:
      src: services/greeter
    taskKey: greet
```

It seems to work correctly with `./services/greeter`

_Originally posted by @NicolasMahe in https://github.com/liteflow-labs/liteflow-js/pull/147_
