### ISSUE TITLE
Error when exit the dev command

### ISSUE THREAD

**Issue by antho1404** [liteflow-labs/liteflow-js#186]
When exiting the dev command there is a connection error.

I think the issue comes from the polling, we probably stop the container and the polling is still in progress.

```
2020-07-10T09:41:25.307Z INFO › result › 8ab157df-7a92-4c95-a94d-6af939bff91c id=8ab157df-7a92-4c95-a94d-6af939bff91c type=SUCCESS price=205000 createdAt=2020-07-10T09:41:24.730Z outputs={"result":{"greetings":"hello foo"}}
^C2020-07-10T09:41:29.655Z INFO › engine › stopping logs 
(node:9803) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:3000
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)
(node:9803) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a c
```

### To reproduce

```js
// myfunction.js
module.exports = (inputs) => {
  const name = inputs.body.name;
  return {
    greetings: `hello ${name || "world"}`,
  };
};
```

```yml
# process.yml
name: my-cloud-function
steps:
  - type: trigger
    endpointKey: my-endpoint
  - type: task
    handler: ./myfunction.js
```

```
liteflow-dev dev
```

`ctrl-C`
