### ISSUE TITLE
Cannot use absolute path in process files

### ISSUE THREAD

**Issue by NicolasMahe** [liteflow-labs/liteflow-js#78]
I cannot put an absolute path to services in the process files. The error is:
`ENOENT: no such file or directory, scandir '../app/Users/nico/Development/liteflow-services/emit-event-interval'`.
The path to the app is prefixed to the path of the service. A test to check if the service path is absolute should be added.
Command used:
```
liteflow-dev dev ../app
```
Process files used:
```yaml
name: test
steps:
  - type: trigger
    key: interval
    instance:
      src: /Users/nico/Development/liteflow-services/emit-event-interval
    eventKey: every_10_seconds
  - type: task
    instance:
      src: /Users/nico/Development/liteflow-services/service-js-function
    taskKey: execute
    inputs:
      code: "module.export = function(value) { return true }"
      inputs:
        foo: 42
```
