### ISSUE TITLE
Deploy stuck at "Creating processes"

### ISSUE THREAD

**Issue by ThomasKientz** [liteflow-labs/liteflow-js#79]
<img width="710" alt="Capture d’écran 2020-04-29 à 10 08 41" src="https://user-images.githubusercontent.com/10157845/80574253-ca308800-8a01-11ea-9380-04416fa71c08.png">

> % liteflow deploy
> ? Type the password of your account [hidden]
> ? Choose a project ETH balance
>   ✔ Compiling processes
> 
> Processes to create
> - balance-notifier (FfwMTBWPtzMD6dj8HUoCxMEXYpfmcApAPg7fp7HwNrmx)
> 
> ? Confirm deploying these processes and all related services Yes
>   ✔ Deploying services
>   ✔ Starting services
>   ❯ Creating processes
>     ⠙ JE06prFZ2IoLuuXuod79/balance-notifier
>       → using account
>     Deleting obsolete processes

**Comment by NicolasMahe** [comment]
Thanks for the bug report.
Which process are you deploying?

**Comment by ThomasKientz** [comment]
Here is my `process.yml`

```yml
name: balance-notifier
steps:
  - type: trigger
    instance:
      src: https://github.com/liteflow-services/emit-event-interval
    eventKey: every_10_seconds
  - type: task
    instance:
      src: https://github.com/liteflow-services/ethereum-erc20
      env:
        - PROVIDER_ENDPOINT=https://mainnet.infura.io/v3/cb3886dab5144dd7a4543994fc667f68
    taskKey: balanceOf
    inputs:
      address: "0x00C9e8D5d439335081a710F342e71a8C3e9fb681"
  - type: task
    instance:
      src: https://github.com/liteflow-services/webhook
    taskKey: call
    inputs:
      url: "https://webhook.site/b2cff87e-9f05-487a-9e75-915f3c2e1f0b"
      data:
        balance: { key: balance }

```

**Comment by NicolasMahe** [comment]
the error should have been fixed. could you try again?

**Comment by NicolasMahe** [comment]
also, the process your are using (from https://docs.liteflow.com/) has been fixed to:
```yaml
name: balance-notifier
steps:
  - type: trigger
    instance:
      src: https://github.com/liteflow-services/emit-event-interval
    eventKey: every_10_seconds
  - type: task
    instance:
      src: https://github.com/liteflow-services/ethereum-erc20
      env:
        - PROVIDER_ENDPOINT=https://mainnet.infura.io/v3/d75ab9cb284f4536b1da2ce9f8201bdb
    taskKey: balanceOf
    inputs:
      contractAddress: "0x420167d87d35c3a249b32ef6225872fbd9ab85d2" # this was missing
      address: "0xe17ee7b3c676701c66b395a35f0df4c2276a344e"
  - type: task
    instance:
      src: https://github.com/liteflow-services/webhook
    taskKey: call
    inputs:
      url: "https://webhook.site/abe438ba-0c54-4594-bdfd-251375006283"
      data:
        balance: { key: balance }
```
