### ISSUE TITLE
Process file convention 

### ISSUE THREAD

**Issue by antho1404** [liteflow-labs/liteflow-js#89]
don't you want to enforce a prefix/suffix? like `XXX.process.yml`?

_Originally posted by @NicolasMahe in https://github.com/liteflow-labs/liteflow-js/pull/88_

**Comment by antho1404** [comment]
I don't really like the idea of having a specific name for the file but I totally understand the issue here. We might have another config file in yaml that will be considered as a process an this is bad.

Just another idea here.
What about having one file standardized (like serverless.yml, docker-compose.yml...) that describes all the application with the processes needed for this application.

Example: `liteflow.yml`
```yml
processes:
  foo: ./foo.yml
  bar: ./bar.yml
```

Going that direction might actually be interesting and we could separate the trigger from the actual process like:
```yml
processes:
   - trigger: 
       instanceHash: xxx
       eventKey: xxx
     steps: ./foo.yml
```
